### ISSUE TITLE
Swap() method for KeyboardBinder

### ISSUE THREAD

**Issue by nullptrException100** [Empiree/DeftSharp.Windows.Input#17]
I propose to create a small method that will change button bindings between each other.

```c#
keyboardBinder.Swap(Key.Q, Key.W)
```

Instead of

```c#
keyboardBinder.Bind(Key.Q, Key.W);
keyboardBinder.Bind(Key.W, Key.Q);
```

But you need to consider the fact that one of these buttons may already be with a different bind. We need to think about what behavior is needed in such a scenario.

**Comment by Empiree** [comment]
Good idea. I think the behavior should be the same if we call these 2 methods separately. If a button already has a different bind, it will simply change to the one we need, just like in the case of calling the Bind method.

**Since this is a method for convenience. It should be added to the KeyboardBinder class directly**
